---
- id: gitmoji-conventional-commit
  name: Gitmoji conventional commit message
  description: >
    Validate that commit messages follow conventional commits, with an
    optional gitmoji at the start of the header.

    - https://www.conventionalcommits.org/en/v1.0.0/
    - https://gitmoji.dev/
  entry: gitmoji-conventional-commit
  language: python
  always_run: true
  pass_filenames: true
  stages: ["commit-msg"]
- id: pre-commit-validate
  name: Validate pre-commit config
  description: >
    Validate the pre-commit configuration file.

    Currently, it only checks that the hook IDs listed in the `ci.skip`
    array exist in the `hooks` section of the configuration file.
  entry: pre-commit-validate
  language: python
  files: ^\.pre-commit-config\.yaml$
- id: tidy-gitkeep
  name: Remove redundant .gitkeep files
  description: >
    Remove redundant .gitkeep files from the repository.

    A `.gitkeep` file is redundant if the directory it is in has any
    other tracked files. The tracked files can be in the same directory
    or in subdirectories.
  entry: tidy-gitkeep
  language: python
  always_run: true
  pass_filenames: false
